service: chatbot

#automatically load environment variables from .env files
useDotenv: true

provider:
  name: aws
  runtime: python3.9


functions:
  listener:
    handler: handler.webhook
  environmentVariables:
    WEBEX_CHATBOT_TOKEN: $WEBEX_CHATBOT_TOKEN

layers:
  lambda-chatbot:
    path: python/
    name: requirementstxt-layer
    description: includes requests library
    compatibleRuntimes:
      - python3.8
      - ptyhon3.9
    compatibleArchitectures:
      - x86_64
    retain: false

package:
  exclude:
    - venv/** # virtualenv